import laser as laser

laser = laser.laser()
laser.update_parameter('laser_model', "81608A")
laser.update_parameter('laser_current_power', '0')
laser.update_parameter('laser_current_wavelength', '1550')
laser.update_parameter('laser_ipAddress',"10.2.137.64")
laser.update_parameter('laser_ipPort',"5025")
laser.update_parameter('laser_inuse','0')
laser.update_parameter('laser_init','0')
laser.update_parameter('laser_slot','0')
laser.update_parameter('laser_power_state','0')
laser.update_parameter('laser_sweep_step_size', '0.0100')
laser.update_parameter('laser_sweep_start_wavelength', '1490.000')
laser.update_parameter('laser_sweep_stop_wavelength', '1640.000')
laser.update_parameter('laser_continuous_sweep_speed', '5.000nm/s')
laser.update_parameter('laser_max_points', '20000')
laser.update_parameter('laser_min_points', '2500')
laser.update_parameter('laser_max_sweep_speed', '5.000')
laser.update_parameter('laser_max_wavelength', '1640')
laser.update_parameter('laser_min_wavelength', '1490')
laser.update_parameter('laser_min_averaging','0.0001')
laser.update_parameter('laser_min_step','0.0001')
laser.update_parameter('laser_sweep_direction','forward')
